<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test1"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="4.774">
  <properties />
            <testcase name="testcase" time="4.774" classname="testng.ApiTestNgVandreamSample">
                <failure type="java.lang.AssertionError"
                  message="did not expect to find [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
  org.testng.Assert.fail(Assert.java:97)
  org.testng.Assert.failNotEquals(Assert.java:969)
  org.testng.Assert.assertTrue(Assert.java:43)
  org.testng.Assert.assertTrue(Assert.java:53)
  testng.ApiTestNgVandreamSample.testcase(ApiTestNgVandreamSample.java:150)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
  org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
  org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
